server:
  port: 8083

spring:
  application:
    name: history-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/history-db}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2.0
          max-attempts: 3

app:
  retention:
    search-days: ${APP_RETENTION_SEARCH_DAYS:180}

management:
  endpoints:
    web:
      exposure:
        include: health
